export const ROOT = 'https://api.spacexdata.com/v3/launches?limit=10';

export const REQUEST_ALLSPACEDETAILS = 'REQUEST_ALLSPACEDETAILS';
export const RECEIVE_ALLSPACEDETAILS = 'RECEIVE_ALLSPACEDETAILS';
export const REQUEST_SPACEDETAILS_LAND = "REQUEST_SPACEDETAILS_LAND"
export const RECEIVE_SPACEDETAILS_LAND ="RECEIVE_SPACEDETAILS_LAND"
export const REQUEST_SPACEDETAILS_LAUNCH = "REQUEST_SPACEDETAILS_LAUNCH"
export const RECEIVE_SPACEDETAILS_LAUNCH ="RECEIVE_SPACEDETAILS_LAUNCH"
export const REQUEST_SPACEDETAILS_YEAR = "REQUEST_SPACEDETAILS_YEAR"
export const RECEIVE_SPACEDETAILS_YEAR = "RECEIVE_SPACEDETAILS_YEAR"
export const REQUEST_SPACEDETAILS_FILTER = "REQUEST_SPACEDETAILS_FILTER"
export const RECEIVE_SPACEDETAILS_FILTER = "RECEIVE_SPACEDETAILS_FILTER"